Name:           perl-Mojo-IOLoop-ForkCall
Version:        0.20
Release:        1%{?dist}
Summary:        (DEPRECATED) run blocking functions asynchronously by forking
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Mojo-IOLoop-ForkCall/
Source0:        https://www.cpan.org/authors/id/J/JB/JBERGER/Mojo-IOLoop-ForkCall-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(IO::Pipely)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Mojolicious) >= 5.08
BuildRequires:  perl(Perl::OSType)
Requires:       perl(IO::Pipely)
Requires:       perl(Mojolicious) >= 5.08
Requires:       perl(Perl::OSType)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
DEPRECATED!

%prep
%setup -q -n Mojo-IOLoop-ForkCall-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install --destdir=$RPM_BUILD_ROOT --create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes ex META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Nov 03 2018 Jarkko Oranen <oranenj@iki.fi> 0.20-1
- Specfile autogenerated by cpanspec 1.78.
